# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimux < Formula
  desc "AI Provider Multiplexer for dev CLIs"
  homepage "https://github.com/MileniumTick/aimux"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.4.2/aimux_0.4.2_darwin_amd64.tar.gz"
      sha256 "6bc87908f4241e16f3fda05ae690e247da1b9731810de6412094544697b06ae0"

      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.4.2/aimux_0.4.2_darwin_arm64.tar.gz"
      sha256 "d55fbf4efe9b26040670f3e2d589cd6f526e38a5ec7169937ea6e160b8245bcf"

      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.4.2/aimux_0.4.2_linux_amd64.tar.gz"
      sha256 "9de51db3b02e720aecbbfbe94ac3a916d5e153abaf53c8e045005c6caca1625f"
      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.4.2/aimux_0.4.2_linux_arm64.tar.gz"
      sha256 "650c6365b69307ca35d1b58d7c57cb02949bf08bc0ced3ca40afc3943f92c8b9"
      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  test do
    system "#{bin}/aimux version"
  end
end
