# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimux" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "0fb798c4dadec869c4b7a77de7b66e62fcdc843d3367b4ee1c26638f305a6cf5"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35cbac789ef12df09d07be0feae27c90066222902d1cc46ad7ba40ed03998470"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb0b8dcdfd477af5071389b185f9c0b3e74183535b3908b15664991fc128d9a0"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5d5730911fbaab5035a2e62960c9defb583bfbafedceb4171d643bddc75496d"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aimux"
  desc "AI Provider Multiplexer for dev CLIs"
  homepage "https://github.com/MileniumTick/aimux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimux"

  # No zap stanza required

end
