# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimux" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "13ad395502926bcf266dda3d24cf49dcfd71d1e901a306c1f389d0ce5aa4c667"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "356ffcb48e07ffa4f1127cb5c2275b72c2c7da182a1e4c830296dbcd64fca79e"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4933e4b783836611e2fef29c886d5996c6ce678a2bc48aa7f537dfc49960215"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dfff761e8bbe490bed032cee4e0d13afb97fb8292516e368770a90d284ccec7a"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aimux"
  desc "AI Provider Multiplexer for dev CLIs"
  homepage "https://github.com/MileniumTick/aimux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimux"

  # No zap stanza required

end
