# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimux" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "b095413cf23154600f7ccfb2431df6e453e65251f21a39b955e274e65b810644"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ae6960dce8248ad98499605c54ede62142cdf14664527a0eb30a1225ad859ab"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d334a8037ca9a8555790555dbbd647093c183b3dee6fa292aca2db22c6ac1b5"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5cc210444ce4d82ae041845ee8ad6f27a1318b226980b0fccf45857cc111a441"
      url "https://github.com/MileniumTick/aimux/releases/download/v#{version}/aimux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aimux"
  desc "AI Provider Multiplexer for dev CLIs"
  homepage "https://github.com/MileniumTick/aimux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimux"

  # No zap stanza required

end
