# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimux < Formula
  desc "AI Provider Multiplexer for dev CLIs"
  homepage "https://github.com/MileniumTick/aimux"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.5.0/aimux_0.5.0_darwin_amd64.tar.gz"
      sha256 "d91574d58cb4bb539753c65b42a042f2598ccbbf5cd941c5711a1144c32e0a69"

      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.5.0/aimux_0.5.0_darwin_arm64.tar.gz"
      sha256 "865d9e338ce0fcc0cf83c973ab1e332af387b39a47cfe447856574ad97c8e6a4"

      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.5.0/aimux_0.5.0_linux_amd64.tar.gz"
      sha256 "257463a9ca9b7f6b8986e5ceea0cc7167cccb0e045d11f082c8567773a757746"
      define_method(:install) do
        bin.install "aimux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MileniumTick/aimux/releases/download/v0.5.0/aimux_0.5.0_linux_arm64.tar.gz"
      sha256 "1db856e8a018cd0bad66e01952599942731f67092e5c0e0537233b98883fb282"
      define_method(:install) do
        bin.install "aimux"
      end
    end
  end

  test do
    system "#{bin}/aimux version"
  end
end
